### ISSUE TITLE
disarray~: uses t_int as integer-type

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#11]
the `iswitch_count()` function uses `t_int` in a way that suggests it is meant to represent a numeric integer type. Pd does not have a "native" integer type (unlike Max).

`t_int` is actually reserved for the pointer array in the DSP-graph, it should not used as a generic type.
(and the `iswitch_count()` function is not used anyhow, so it should probably be just removed entirely)

**Comment by ericlyon** [comment]
Good point.
