### ISSUE TITLE
(not) including m_pd.h

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#12]
i noticed that fftease3.0 includes an `m_pd.h` header file that is more than ten years old (it comes from _Pd-0.38_).

I would suggest to _not_ include the header-file at all, but instead use the header-files installed on the system.
- this would ensure that the header-file actually matches the version of Pd installed
- this would _allow_ people who would like to use a recent header file to actually do so (the current setup makes this basically impossible, as the header is included via `"m_pd.h"` (with double quotes) which makes sure that it is first searched in the current directory).

now `m_pd.h` is not changing _very much_ (luckily, as that's the reason why fftease does not immediately segfault when run with any Pd released within the last 10 years).
nevertheless it _does_ change a bit.

I understand that the reasoning behind providing a local copy of the header file is to ease compilation (and not have to worry about the actual location on non-standardized platforms like OSX and W32).

however, the current scheme doesn't really work on W32 (as this requires not only the header-file but also some `pd.lib` during linking).

one portable solution to allow both the inclusion of the header (and it's use by default) and the use of a system provided header, would be to:
- move the header into a subdirectory
- set the `PD_INCLUDE` variable in the Makefile to this subdirectory.

this would allow the savvy user to override the include path with something like:

```
make PD_INCLUDE=/usr/include/pd/
```

(btw, as an extra bonus this is the canonical way of the template-Makefile to set the search path for Pd-headers)

**Comment by ericlyon** [comment]
That would be a change for the next major version of fftease. I would like to have one version that is guaranteed not to break when the header file changes.

**Comment by umlaeute** [comment]
closed with #18
