### ISSUE TITLE
Output explodes and distorts on 0.46.7

### ISSUE THREAD

**Issue by boonier** [ericlyon/pd-fftease#13]
I've been having troubles with the latest Pd vanilla and FFTease 2.5.2 and also this latest version. Do you have any ideas, or recommendations on what to do?

Running on OSX 10.10.5.

Thanks

**Comment by ericlyon** [comment]
Please send a specific patch, and precise explanation of what went wrong
and I will have a look. Also let me know what versions of Pd work for you.

Best,

Eric

**Comment by boonier** [comment]
Hi Eric

Thanks, actually I've got another new issue. I've got my paths set up normally (afaiks), but I try to instantiate a thresher~ object and get an error:

```
/Users/boonier/Dropbox/Audio Work/pure data/Pd/fftease/thresher~.pd_darwin: dlopen(/Users/boonier/Dropbox/Audio Work/pure data/Pd/fftease/thresher~.pd_darwin, 10): Symbol not found: _convert
  Referenced from: /Users/boonier/Dropbox/Audio Work/pure data/Pd/fftease/thresher~.pd_darwin
  Expected in: /Users/boonier/Dropbox/Audio Work/pure data/Pd/fftease/libfftease.dylib

 thresher~
... couldn't create
```

I've tried in both 0.46.7 and 0.44 (extended). 

The original problem of the output exploding was just on the basic help patch files (when it was loading correctly). Sorry I cannot be more specific!

Much thanks
Si

**Comment by ericlyon** [comment]
I just did a quick test on OSX 10.11.1, Pd 0.46.7 and could not recreate
either issue. Perhaps you do not have the software correctly installed. I
recommend deleting any old copies of FFTease and try reinstalling from
scratch.

https://github.com/ericlyon/fftease3.0-32bit

Good luck!

Eric

**Comment by boonier** [comment]
OK I got it working. I had to rebuild the externals on my machine. There is a new libfftease.dylib file that is required, right? Also I had the old help files which probably didn't help!

Thanks for your help
Si

**Comment by ericlyon** [comment]
Glad to hear that it worked out!

Eric

**Comment by boonier** [comment]
Ha cheers. Is the block size/overlap set differently now? The help patches
don't have the same mechanism

thanks

**Comment by ericlyon** [comment]
First argument is the FFT size. Second argument is the overlap factor.
Defaults are 1024 and 8.

Best,

Eric

**Comment by boonier** [comment]
Nice! If I want to update the window sizes on the fly, what are the
messages to send to the object?

[fftsize 512, overlap 4( for example doesn't work.

Thanks

**Comment by ericlyon** [comment]
Not an option in this version. Makes the objects more stable.

**Comment by umlaeute** [comment]
@ericlyon can this issue be closed? (if so, just click on the <kbd>Close issue</kbd> button at the end)

justification:
- ["got it working"](https://github.com/ericlyon/pd-fftease/issues/13#issuecomment-162904557)
- issue not reproducible in the first place
