### ISSUE TITLE
suggested repository cleanups

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#16]
i think this repository is a great mess.
here's a few suggestion on how to improve it (and make it a joy to work with).
(i hope i'm not being to snarky)

- [x] rename repository to `fftease`
  - or - if you want to keep the Max/MSP source-base separate from the Pd sources - to `pd-fftease` or somesuch
  - use *git tags* for versions
  - strive to support 32bit and 64bit (and single- and double-precision) in a single repository - if necessary in multiple branches
- [x] remove all build-artifacts 
 - don't abuse the *source* repository for delivering binaries. 
   - you can attach "release-artifacts" (any file you like) to a tagged release. so people who don't want to compile themselves are not forced through git, but can simply get the latest and greatest fftease.
   - even better: use `deken` to publish your binaries, so people can install fftease from within Pd and not have to worry at all about github and the likes.
- [x] remove 3rd party files (namely `m_pd.h`; see #12)
  - this is the only sane way to ever support double-precision
- [x] switch the buildsystem to [pd-lib-builder](https://github.com/pure-data/pd-lib-builder)
  - the template Makefile was nice back then. pd-lib-builder is the next generation build system and helps *tremendously* if you don't want to worry about building on platforms you don't actively use.

**Comment by ericlyon** [comment]
> i think this repository is a great mess.
> here's a few suggestion on how to improve it (and make it a joy to work with).
> (i hope i'm not being to snarky)

You are.

> 
> * [ ]  rename repository to `fftease`
>   

No.

>   * or - if you want to keep the Max/MSP source-base separate from the Pd sources - to `pd-fftease` or somesuch
>   * use _git tags_ for versions
>   * strive to support 32bit and 64bit (and single- and double-precision) in a single repository - if necessary in multiple branches

That is a good idea. fftease-pd would be a good name for a repo that supports both 32-bit and 64-bit.

> * [ ]  remove all build-artifacts

Agree.

> * don't abuse the _source_ repository for delivering binaries.
>   

Abuse is in the eye of the beholder. I'm fine with removing the binaries, if they can be put somewhere else easily accessible to non-programmer Pd users.

>   * you can attach "release-artifacts" (any file you like) to a tagged release. so people who don't want to compile themselves are not forced through git, but can simply get the latest and greatest fftease.

Sounds good. I don't have time to do that.

>   * even better: use `deken` to publish your binaries, so people can install fftease from within Pd and not have to worry at all about github and the likes.

Sounds good. I don't have time to do that.

> * [ ]  remove 3rd party files (namely `m_pd.h`; see #12)
>   

Definitely agree with this one.

>   * this is the only sane way to ever support double-precision
> * [ ]  switch the buildsystem to [pd-lib-builder](https://github.com/pure-data/pd-lib-builder)
>   

Don't know anything about that system, but I'm happy merge it, if someone else wants to make that switch.

>   * the template Makefile was nice back then. pd-lib-builder is the next generation build system and helps _tremendously_ if you don't want to worry about building on platforms you don't actively use.

Thanks for the feedback.

Eric

**Comment by Lucarda** [comment]
@ericlyon there are things that we can do when we find time to do PRs but can you start renaming the repository to fftease-pd or pd-fftease. (I agree with @umlaeute that the latter is the standard but this is your lib)

**Comment by ericlyon** [comment]
> @ericlyon there are things that we can do when we find time to do PRs but can you start renaming the repository to fftease-pd or pd-fftease. (I agree with @umlaeute that the latter is the standard but this is your lib)

Done!

**Comment by Lucarda** [comment]
Cool :)

Can you make an "initial release" ? (mainly a backup)

Go to "https://github.com/ericlyon/pd-fftease/releases" and use the button "Draft a new release".

Here give it a name ("initial release" is good enough for me)

Then you can add the a zip package with the macOS binaries that are currently on the folder "fftease32-externals"
There's an area where you can drop the zip file. The zip package containing the binaries will *not* be auto generated, you must supply it. Here you upload the different OS/Arch binaries ready to use for a normal Pd user. (uploading to Deken is obliviously better)

A source code package *will be* auto-generated with the current state of the repository

Next move will be in PRs (probably the first one will be to delete the "fftease32-externals" folder from the repository.

**Comment by Lucarda** [comment]
this pic shows an example of a release section:

![Untitled](https://user-images.githubusercontent.com/25239522/100294529-d06def00-2f65-11eb-8521-7b8ac42cbff6.png)

**Comment by ericlyon** [comment]
Thanks! I just published a pre-release. I'll look into uploading the binaries, though it may make sense to wait until we can upload binaries compiled from the code after it has been updated.

**Comment by Lucarda** [comment]
> I'll look into uploading the binaries, though it may make sense to wait until we can upload binaries compiled from the code after it has been updated.

Ok no trouble. The macOS binaries are in the release (source) package you just created. That why we want this folder out of the repo.

**Comment by ericlyon** [comment]
It's fine to remove the binaries from the source tree.

**Comment by Lucarda** [comment]
@ericlyon see PR #18.

:)

**Comment by Lucarda** [comment]
@ericlyon see #19 that finishes the clean up and includes [pd-lib-builder](https://github.com/pure-data/pd-lib-builder)

**Comment by umlaeute** [comment]
closing this, as all my points have been implemented ;-)

thanks a lot!
