### ISSUE TITLE
burrow~ invert message at creation

### ISSUE THREAD

**Issue by porres** [ericlyon/pd-fftease#27]
if you have a loadbang setting the invert message to 1, it doesn't work. You have to wait a little until setting this in order for it to work

**Comment by ericlyon** [comment]
This seems to be true for other messages as well. Same thing for "mute." I don't see any issues in the code, and the corresponding loadbang initiation works correctly on Max/MSP. Perhaps, for whatever reason, the loadbang triggers its message before the receiving object is instantiated. I don't have time to test right now, but it's worth checking to see if this issue occurs with the other FFTease objects.

**Comment by porres** [comment]
>  I don't have time to test right now, but it's worth checking to see if this issue occurs with the other FFTease objects.

Ok, I can check for solutions on the code later, but right now I'm working on the docs ;)

**Comment by ericlyon** [comment]
A "pipe 0" after the loadbang solves the problem.

**Comment by ericlyon** [comment]
Looks like there was an initialization bug in the code. I'll try to figure out how to upload a new version soon.

**Comment by ericlyon** [comment]
Done. There's a diagnostic post() message in the code. I'll take it out soon, if no new problems were introduced.

**Comment by porres** [comment]
This issue seems to be a duplicate of https://github.com/ericlyon/pd-fftease/issues/5

we can close the old one (and keep this open until you remove that post() message (I could do that later as well)

**Comment by ericlyon** [comment]
Sounds like you're on a roll, so you're welcome to remove that post message if you like :)

**Comment by porres** [comment]
> Sounds like you're on a roll, so you're welcome to remove that post message if you like :)

I can't :) only iohannes who opened that old one can close it or you... unless you give me some superpowers and I don't know how you can do that

**Comment by porres** [comment]
not sure if it's clear in my joking tone, but it is possible I join as a collaborator and be granted such powers, I just have no idea how it works

**Comment by ericlyon** [comment]
Of course. I know next to nothing about how to use Github, so I'm not sure what I need to do, if anything. Are you not able to submit Pull Requests right now?
