### ISSUE TITLE
pvwarp~ bottomfreq/topfreq not working when DSP is off

### ISSUE THREAD

**Issue by porres** [ericlyon/pd-fftease#28]
these messages need to know Pd's sample rate and that is only obtained by the object if the DSP is on. So if you create the object and try to set it without the DSP on, it just gives an error.

What we need to do is get Pd's sample rate at creation time. I already did this here and could send a PR later.

**Comment by ericlyon** [comment]
Excellent, thanks!

**Comment by porres** [comment]
check out https://github.com/ericlyon/pd-fftease/pull/33 it fixes this, I tested and it seems fine
