### ISSUE TITLE
repository cleanup

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#32]
i guess it's time to remove the "pr/1" branch:
- navigate to https://github.com/ericlyon/pd-fftease/branches
- click the trashbin icon <kbd>🗑️</kbd> besides the "pr/1" branch
- confirm

the webinterface indicates that there are 3 unmerged commits, however:
- 255b7735b990c2b18f375ea5d25df10b3f6adb47 and 1cda1734d72b11b90f8d00e8cfc92aca0ff9c6a8 are only merge commits from the `master` branch (and ar ethus included in the current `master`)
- 7fd01583dd4ae16230f9972ed0ab37baa1e46acf is been included as it's "duplicate" c20c314a609f6083418b156033c52af1d0c70abf

**Comment by ericlyon** [comment]
Done!
