### ISSUE TITLE
to do list for an official 3.0 release

### ISSUE THREAD

**Issue by porres** [ericlyon/pd-fftease#36]
Just opening this to see what is it that we have on a "to do" list before uploading an official release, feel free to edit this comment.
- Complete the readme, with full instructions for installation
- Possibly recast the Readme file in .md format for better look
- Provide pre-compiled externals for macOS, linux, and windows

**Comment by ericlyon** [comment]
#34 is fixed. I'll work on the readme. Let me take a moment to thank everyone who contributed to this update. There's no way I would have had time to do this project on my own. It's great that we've discovered and fixed some long-standing bugs. I've migrated these bug fixes back to the Max/MSP versions. Everybody wins :)

 @porres @umlaeute @Lucarda

**Comment by umlaeute** [comment]
btw, if you want a TODO-list for the next release, you should look gitub's [milestones](https://github.com/ericlyon/pd-fftease/milestones/) feature, which allows you to easily attach issues to common target.

**Comment by ericlyon** [comment]
> btw, if you want a TODO-list for the next release, you should look gitub's [milestones](https://github.com/ericlyon/pd-fftease/milestones/) feature, which allows you to easily attach issues to common target.

Thanks for the suggestion. Milestones look a bit more complicated than a todo list. That being said, I'm willing to consider using milestones, if it makes the development process easier for people. For now, let's focus on getting this release out the door, and then we can return to the question.

**Comment by umlaeute** [comment]
your call.
milestones are simple insofar as you can just associate any issue you want with one (or more) milestones, so the TODO-list automatically grows (and shrinks) as new issues show up.

but it's really up to you, and if you find them too tedious then best leave them.

**Comment by ericlyon** [comment]
Cool. We can give milestones a try after this release, and see how people like them.

**Comment by ericlyon** [comment]
Can anyone provide a Windows 10 build of these externals that can be attached to the release as an asset?

**Comment by porres** [comment]
@Lucarda surely can ;)

**Comment by ericlyon** [comment]
Excellent. Could we get a Linux build too? Once those assets are in place, I'll make a proper announcement on the Pd list and we can go from there. Maybe have a look at pd-lyonpotpourri next. I'm teaching with Pd this semester, so it would be cool if my students could actually use some of my externals :)

**Comment by Lucarda** [comment]
>Excellent. Could we get a Linux build too?

@ericlyon [click here](https://nc.nubegris.com.ar/index.php/s/YiqfEfMSC9FmJQQ) to download builds for Windows/Linux 32/64 (4 builds).

Notes: May be there's a way to update the help patches of the following objects so that we don't get errors in the console when DSP is on:

`````
<[ FFTease 3.0 ]>   |   ( codepend~ )
incorrect FFT size specified, using 1024
incorrect FFT size specified, using 1024

<[ FFTease 3.0 ]>   |   ( enrich~ )
player~: buf: no such array

<[ FFTease 3.0 ]>   |   ( pvwarpb~ )
player~: buf: no such array

<[ FFTease 3.0 ]>   |   ( residency_buffer~ )
player~: buf: no such array
`````

> Maybe have a look at pd-lyonpotpourri next

Cool. I have uploaded to Deken Win64 builds (and they are working):

`````
lyonpotpourri[v0.3](Windows-amd64-32)(Sources).dek
	Uploaded by lucarda @ 2019-11-19 04:34:34


`````

**Comment by umlaeute** [comment]
very minor nitpick: could we talk about `i386` (or i686; or x86_32) resp. `amd64` (or x86_64) rather than just *32* or *64*.
there are *many* different 32bit and 64bit platforms (think arm; but there's many many more)

**Comment by Lucarda** [comment]
@umlaeute Ok. I'll try to update my mind. :)

**Comment by umlaeute** [comment]
> Cool. I have uploaded to Deken Win64 builds (and they are working):

are you sure?
looking at the source code, there should be a problem with the `[vdp~`] object (esp. the `copy_to_buffer` message).

however, this should be tracked in https://github.com/ericlyon/pd-lyonpotpourri

**Comment by Lucarda** [comment]
hmm no, not sure. IIRC I tested all objects and they were Ok. I may have to re-test them.

**Comment by Lucarda** [comment]
I did a quick check on Win(amd64) and the [vdp~] object does not throw errors to the console and it works.

Here is the console after opening all help patches:



```
-<LyonPotpourri 3.0>- (  windowvec~  )
-<LyonPotpourri 3.0>- (  cartopol~  )
-<LyonPotpourri 3.0>- (  poltocar~  )
-<LyonPotpourri 3.0>- (  arrayfilt~  )
-<LyonPotpourri 3.0>- (  samm~  )
-<LyonPotpourri 3.0>- (  player~  )
-<LyonPotpourri 3.0>- (  mask~  )
-<LyonPotpourri 3.0>- (  vdp~  )
-<LyonPotpourri 3.0>- (  bashfest~  )
-<LyonPotpourri 3.0>- (  buffet~  )
 impulse~
... couldn't create
... you might be able to track this down from the Find menu.
-<LyonPotpourri 3.0>- (  bvplay~  )
-<LyonPotpourri 3.0>- (  channel~  )
-<LyonPotpourri 3.0>- (  chopper~  )
force loop: bindex -1 is out of range
frames:62079 start:-1, samps2go:12992, tloopsamps:75071, increment:-1.000000
-<LyonPotpourri 3.0>- (  clean_selector~  )
-<LyonPotpourri 3.0>- (  click2bang~  )
-<LyonPotpourri 3.0>- (  click2float~  )
-<LyonPotpourri 3.0>- (  clickhold~  )
-<LyonPotpourri 3.0>- (  click~  )
-<LyonPotpourri 3.0>- (  convolver~  )
-<LyonPotpourri 3.0>- (  counter~  )
-<LyonPotpourri 3.0>- (  distortion~  )
-<LyonPotpourri 3.0>- (  dmach~  )
-<LyonPotpourri 3.0>- (  adsr~  )
-<LyonPotpourri 3.0>- (  oscil~  )
-<LyonPotpourri 3.0>- (  dynss~  )
-<LyonPotpourri 3.0>- (  epluribus~  )
-<LyonPotpourri 3.0>- (  killdc~  )
-<LyonPotpourri 3.0>- (  expflam~  )
-<LyonPotpourri 3.0>- (  flanjah~  )
-<LyonPotpourri 3.0>- (  function~  )
-<LyonPotpourri 3.0>- (  granola~  )
-<LyonPotpourri 3.0>- (  granulesf~  )
-<LyonPotpourri 3.0>- (  granule~  )
-<LyonPotpourri 3.0>- (  kbuffer~  )
-<LyonPotpourri 3.0>- (  latch~  )
-<LyonPotpourri 3.0>- (  magfreq_analysis~  )
-<LyonPotpourri 3.0>- (  markov~  )
-<LyonPotpourri 3.0>- (  npan~  )
-<LyonPotpourri 3.0>- (  phasemod~  )
-<LyonPotpourri 3.0>- (  pulser~  )
-<LyonPotpourri 3.0>- (  quadpan~  )
-<LyonPotpourri 3.0>- (  rotapan~  )
-<LyonPotpourri 3.0>- (  shoehorn~  )
-<LyonPotpourri 3.0>- (  rtrig~  )
-<LyonPotpourri 3.0>- (  sarec~  )
-<LyonPotpourri 3.0>- (  sel~  )
-<LyonPotpourri 3.0>- (  sigseq~  )
-<LyonPotpourri 3.0>- (  splitbank~  )
-<LyonPotpourri 3.0>- (  splitspec~  )
-<LyonPotpourri 3.0>- (  squash~  )
-<LyonPotpourri 3.0>- (  stutter~  )
-<LyonPotpourri 3.0>- (  vdb~  )
 greater~ 20
... couldn't create
-<LyonPotpourri 3.0>- (  vecdex~  )
-<LyonPotpourri 3.0>- (  waveshape~  )
```

**Comment by umlaeute** [comment]
@Lucarda see https://github.com/ericlyon/pd-lyonpotpourri/issues/4

should we remove all the comments since (and including) https://github.com/ericlyon/pd-fftease/issues/36#issuecomment-773210384 ?

**Comment by Lucarda** [comment]
> should we remove all the comments since (and including) #36 (comment) ?

yes

**Comment by ericlyon** [comment]
The repeated error messages to console have been fixed in enrich~. I'll need to update the other two objects similarly. The helpfiles will require separate attention.

**Comment by ericlyon** [comment]
> > Excellent. Could we get a Linux build too?
> 
> @ericlyon [click here](https://nc.nubegris.com.ar/index.php/s/YiqfEfMSC9FmJQQ) to download builds for Windows/Linux 32/64 (4 builds).
> 
> Notes: May be there's a way to update the help patches of the following objects so that we don't get errors in the console when DSP is on:
> 
> ```
> <[ FFTease 3.0 ]>   |   ( codepend~ )
> incorrect FFT size specified, using 1024
> incorrect FFT size specified, using 1024
> 
> <[ FFTease 3.0 ]>   |   ( enrich~ )
> player~: buf: no such array
> 
> <[ FFTease 3.0 ]>   |   ( pvwarpb~ )
> player~: buf: no such array
> 
> <[ FFTease 3.0 ]>   |   ( residency_buffer~ )
> player~: buf: no such array
> ```
> 
> > Maybe have a look at pd-lyonpotpourri next
> 
> Cool. I have uploaded to Deken Win64 builds (and they are working):
> 
> ```
> lyonpotpourri[v0.3](Windows-amd64-32)(Sources).dek
> 	Uploaded by lucarda @ 2019-11-19 04:34:34
> ```

enrich~, pvwarbp~, and residency_buffer~ have been updated. The codepend~ help file has been updated. Good finds here, hopefully now fixed.

**Comment by Lucarda** [comment]
> enrich~, pvwarbp~, and residency_buffer~ have been updated. The codepend~ help file has been updated. Good finds here, hopefully now fixed.

Cool. The new Windows and Linux binaries are [here](https://nc.nubegris.com.ar/index.php/s/ZY6W6XM9C2oQQ7r).

I think this is ready for a release. The only (really minor) thing is that we get this errors in the help patches:


```
enrich~: buf: no such array
pvwarpb~: buf: no such array
residency_buffer~: buf: no such array
```


This can be fixed including an [array buf 10000] in those help patches but that will pollute the nice and clean work by @porres so If anyone ask me: this is ready to go.

:)

**Comment by ericlyon** [comment]
New binaries added to release. Thanks, @Lucarda. I think the help files could all be fixed by replacing "buf" with the existing arrray in each of those help files. Hopefully that wouldn't be too aesthetically unpleasant.

**Comment by ericlyon** [comment]
Let's toss this around for the weekend, and see if any last-minute issues emerge. If not, I'll announce the release to the Pd list on Monday. Thanks again, everyone, for all of your contributions to this project. Once release is out, I invite you to turn your attention to pd-lyonpotpourri.

**Comment by Lucarda** [comment]
All good. 

Probably you should familiarize with Deken(1) so that we can install fftease via Pd's menu: help / find externals. 


> Once this release is out, I invite you to turn your attention to pd-lyonpotpourri.

Count me in. :)


(1) https://github.com/pure-data/deken/blob/master/developer/README.md

**Comment by porres** [comment]
> Cool. The new Windows and Linux binaries are here.
> 
> I think this is ready for a release. The only (really minor) thing is that we get this errors in the help patches:
> 
> enrich~: buf: no such array
> pvwarpb~: buf: no such array
> residency_buffer~: buf: no such array
> This can be fixed including an [array buf 10000] in those help patches but that will pollute the nice and clean work by @porres so If anyone ask me: this is ready to go.
> 
> :)

hey, these help files issues have been updated and fixed for a while, you don't seem to have the updated version @Lucarda

**Comment by porres** [comment]
I tested all files and I get "mindwarp~: zero warp factor is illegal"

**Comment by Lucarda** [comment]
> hey, these help files issues have been updated and fixed for a while, you don't seem to have the updated version @Lucarda

Strange I used the master branch as of 5da7a7d.

> I tested all help files with DSP on and the error I get is "mindwarp~: zero warp factor is illegal"

Could not replicate on Windows or Linux.

**Comment by ericlyon** [comment]
> > I tested all help files with DSP on and the error I get is "mindwarp~: zero warp factor is illegal"
> 
> Could not replicate on Windows or Linux.

I could not replicate on MacOS Catalina.

**Comment by ericlyon** [comment]
> > Cool. The new Windows and Linux binaries are here.
> > I think this is ready for a release. The only (really minor) thing is that we get this errors in the help patches:
> > enrich~: buf: no such array
> > pvwarpb~: buf: no such array
> > residency_buffer~: buf: no such array
> > This can be fixed including an [array buf 10000] in those help patches but that will pollute the nice and clean work by @porres so If anyone ask me: this is ready to go.
> > :)
> 
> hey, these help files issues have been updated and fixed for a while, you don't seem to have the updated version @Lucarda

@porres, I'm also seeing the same issue on what I'm pretty sure is the current master :) That is, the enrich~ help file has "buf" as the argument for the top copy of enrich~. Would a new pull request solve this?

**Comment by porres** [comment]
Ok, so I had changed it in my fork and did not make a Pull Request, so here it is now https://github.com/ericlyon/pd-fftease/pull/39

**Comment by porres** [comment]
I recompiled and tested all help files now with DSP On and see no issues!

**Comment by porres** [comment]
> Probably you should familiarize with Deken(1) so that we can install fftease via Pd's menu: help / find externals.

I can upload it all to deken

> Let's toss this around for the weekend, and see if any last-minute issues emerge. If not, I'll announce the release to the Pd list on Monday. 

I think we need to make a new tag release here https://github.com/ericlyon/pd-fftease/releases

It seems safe now that we have a release, so we can upload the binaries there and also to deken, but maybe make a few tests before uploading to deken and announcing it.

**Comment by Lucarda** [comment]
I know there's nothing relevant on the c files after 5da7a7d but I will recompile and test anyway and give new win/linux binaries.

**Comment by Lucarda** [comment]
@porres can you change these:  
  
  

- bthresher~: does not have the object at top-right (near the description)  
- multyq~: has an empty/uncreated object
- pvharm~: font size  
- pvwarp~: font size and screen xy

**Comment by porres** [comment]
changed, see https://github.com/ericlyon/pd-fftease/pull/40

> pvwarp~: font size and screen xy

not really sure what you meant by "xy"

**Comment by Lucarda** [comment]
> not really sure what you meant by "screen xy"

Window position. On my screen is too far right. The other patches are more to the left.

**Comment by porres** [comment]
how is  it now?

**Comment by Lucarda** [comment]
Nice :)
I'll make new linux/windows build pkgs.

**Comment by Lucarda** [comment]
@ericlyon 

The linux/windows builds (as of aa031e8) are [here](https://nc.nubegris.com.ar/index.php/s/PnNNT6g9ygWxHNw)

**Comment by ericlyon** [comment]
Thanks. The release has been updated with these binaries.

**Comment by porres** [comment]
> Thanks. The release has been updated with these binaries.

Hi, it seems you uploaded the binaries to https://github.com/ericlyon/pd-fftease/releases/tag/v3.0.0-alpha

See that is an old state of the repository, marked as "alpha", the source code there, also provided as a download is an old source code.

Therefore you need to create a new tag and release here https://github.com/ericlyon/pd-fftease/releases/ for a new release that corresponds to the source code from that tag.

byt first, I made another change at https://github.com/ericlyon/pd-fftease/pull/41 that includes copying readme.md to the installation

I see that the binaries/packages provided by @Lucarda are ok, but the macOS version only includes the binaries. I can make a package for macOS but using pd-lib-builder, what I advise you to do is:

"make install objectsdir=../ extension=d_fat"

this will create a folder for fftease with the help files, the readme, etc and the binaries will work for both Pd 32 bits or 64 bits

**Comment by porres** [comment]
here's the pack [fftease.zip](https://github.com/ericlyon/pd-fftease/files/5936940/fftease.zip)

@Lucarda , can you just include the readme.md file in your packages (so yu don't have to rebuild them)?

**Comment by ericlyon** [comment]
> > Thanks. The release has been updated with these binaries.
> 
> Hi, it seems you uploaded the binaries to https://github.com/ericlyon/pd-fftease/releases/tag/v3.0.0-alpha
> 
> See that is an old state of the repository, marked as "alpha", the source code there, also provided as a download is an old source code.
> 
> Therefore you need to create a new tag and release here https://github.com/ericlyon/pd-fftease/releases/ for a new release that corresponds to the source code from that tag.
> 
> byt first, I made another change at #41 that includes copying readme.md to the installation
> 
> I see that the binaries/packages provided by @Lucarda are ok, but the macOS version only includes the binaries. I can make a package for macOS but using pd-lib-builder, what I advise you to do is:
> 
> "make install objectsdir=../ extension=d_fat"
> 
> this will create a folder for fftease with the help files, the readme, etc and the binaries will work for both Pd 32 bits or 64 bits

There are a few different issues here. First, it looks like "Readme.md" is in the already installation, so I'm not sure why we need another copy of the Readme as a ".txt." Am I missing something?

Next, how do I make a new tag? Hit the "Draft a new release" button? If so, what should the new tag be called?

Finally, I tried the make command you suggested, and I'm not sure the resulting binaries actually are fat. I'm seeing these warning messages from the compiler:

ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd (3 slices)
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)

Maybe better to just build as 64-bit?

Please advise. Thanks!

**Comment by porres** [comment]
> There are a few different issues here. First, it looks like "Readme.md" is in the already installation, so I'm not sure why we need another copy of the Readme as a ".txt." Am I missing something?

You had a readme.txt file that was getting copied in the installation via the makefile. But now you replaced it for a readme.md file, when in the makefile you still had "readme.txt" instead of the new "readme.md", so the nw "readme.md" file wasn't getting copied in the installation process, and since you don't have readme.txt anymore, when the makefile tried copying this file, nothing happened.

I checked the packages by @Lucarda and they did not include readme.md

So my Pull Request ( https://github.com/ericlyon/pd-fftease/pull/41 ) just changes the old extension for the new one, see=> https://github.com/ericlyon/pd-fftease/pull/41/files

**Comment by porres** [comment]
> Next, how do I make a new tag? Hit the "Draft a new release" button?

yes

>  If so, what should the new tag be called?

the tag you have there now is 3.0.0-alpha, I guess 3.0.0 is alright now :) we can just consider this old one as "alpha"

**Comment by porres** [comment]
> Finally, I tried the make command you suggested, and I'm not sure the resulting binaries actually are fat.

you mean you're not sure they work? Cause if they come out as "d_fat", they're fat :) 

> I'm seeing these warning messages from the compiler:
> 
> ld: warning: The i386 architecture is deprecated for macOS (remove from the Xcode build setting: ARCHS)
> ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libc.tbd (3 slices)
> ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, missing required architecture i386 in file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd (3 slices)
> 

I do get the same warnings, but I'm in Mojave, so I can test the builds on both Pd 32 or 64 bits. And they work on both, so I can assure at least my build is fat and good for both systems.

> Maybe better to just build as 64-bit?
> 
> Please advise. Thanks!

It is 64 bits AND 32 bits as well :) we can also provide a single 64 bits "pd_darwin" extension as well, but I don't think that's necessary since this one works for both. And it's good to provide an option for 32 bits as well cause some people still use the 32 bits version so they can run some old externals. At least I think so, but we can take it to the Pd list and see what others have to say, like @umlaeute  ;)

**Comment by ericlyon** [comment]
Maybe it's better for you to compile the macOS binaries in that case. I'm on Catalina, so I'm not sure my build will work for 32-bit. Still working on the new tag. Will hopefully have that up soon.

**Comment by porres** [comment]
no problem, I can send my build, and I can also test yours just so we know ;)

**Comment by porres** [comment]
> we can take it to the Pd

just sent an email there

**Comment by ericlyon** [comment]
Just created the new release tag.

**Comment by porres** [comment]
here's my build you can upload there [fftease_macOS.zip](https://github.com/ericlyon/pd-fftease/files/5937004/fftease_macOS.zip)

I guess you'll need to delete the other ones from https://github.com/ericlyon/pd-fftease/releases/tag/v3.0.0-alpha now

and @Lucarda can send you new packages containing the readme.md file and all, then we're done for the release and I can also upload them to deken

**Comment by ericlyon** [comment]
I just uploaded my own build to the new v3.0.0 tag. Could you please check these out, and see if the binaries work for 32-bit as well as 64-bit?

Is the idea to delete the v3.0.0-alpha tag entirely, or just remove the assets?

**Comment by porres** [comment]
just remove the assets

**Comment by ericlyon** [comment]
Done.

**Comment by porres** [comment]
> Could you please check these out, and see if the binaries work for 32-bit as well as 64-bit?

THEY WORK FOR BOTH!!!

BUT...... you just have the binaries in that zip, no help files and nothing else! It seems you didn't run the "make install" or something. Also, the folder uncompresses to a "pd-fftease-MacOS" folder. The one I provided above has it all and uncompresses to just "fftease". Now that we tested that externals built in catalina work for 32 bits, maybe you can just replace that asset with my build.

**Comment by ericlyon** [comment]
Excellent. I swapped in your build.

**Comment by porres** [comment]
great, all we need now is the new packages by @Lucarda and we're done :)

**Comment by porres** [comment]
so, I already took the liberty to upload the 3.0.0 version of fftease for macOS to deken. Here's a screenshot.


<img width="677" alt="Screen Shot 2021-02-06 at 12 56 03" src="https://user-images.githubusercontent.com/5360142/107123154-b2344180-687a-11eb-8624-3847d0a28f2c.png">

I can see @Lucarda has uploaded at some point 3.0 versions for linux and windows. I suggest we take those out to avoid confusion. Then I can upload the new "3.0.0" ones for the remaining systems

**Comment by ericlyon** [comment]
Great. Could you please also upload the macOS version?

**Comment by porres** [comment]
I did upload the macOS version ;) that's the one, it's for both 32 and 64 bits.

just waiting for @Lucarda's builds for both windows/linux 32/64 to upload them too

oh, and I now uploaded the source code as well

<img width="671" alt="Screen Shot 2021-02-06 at 13 10 38" src="https://user-images.githubusercontent.com/5360142/107123523-bd886c80-687c-11eb-9886-caef0240b6d1.png">

**Comment by ericlyon** [comment]
I can see it from Pd now. Nice.

**Comment by Lucarda** [comment]
@ericlyon the linux/windows builds (as of 06ebfb0) are [here](https://nc.nubegris.com.ar/index.php/s/ENq4d6xHZZQ893x)


I had uploaded the new linux/win packages to Deken and also removed the offending and old [v3.0] packages.

:)

**Comment by porres** [comment]
I guess we can leave this as is and call it a release and announce it to the Pd list and all, just a couple of notes under scrutiny:

- the 3.0.0 tagged release (https://github.com/ericlyon/pd-fftease/releases/tag/3.0.0) is a commit behind https://github.com/ericlyon/pd-fftease/commit/06ebfb0432700ae7f66b8841abdd931cac415760 - let's just be careful to make builds that are 100% synced with the tags. Having said all that, this ain't a big deal.

- why do we have a lyonpotpourri meta in fftease? :) that's what the last commit did update anyway... well, I'm removing it in my latest pull request - https://github.com/ericlyon/pd-fftease/pull/43 . Again, we can just live with this for now. I'm just saying I'm not imposing we ~have~ to redo this just to fix this, but I'm not objecting this either.

**Comment by ericlyon** [comment]
> * why do we have a lyonpotpourri meta in fftease? :) that's what the last commit did update anyway... well, I'm removing it in my latest pull request - #43 . Again, we can just live with this for now. I'm just saying I'm not imposing we ~have~ to redo this just to fix this, but I'm not objecting this either.

Nice catch. No idea what a lyonpotpourri file was doing there. Also, for post-release I opened up #42 to discuss further upgrades to the FFTease documentation.

**Comment by porres** [comment]
>  Also, for post-release I opened up #42 to discuss further upgrades to the FFTease documentation.

ok

**Comment by porres** [comment]
well, I guess the release is done and I can close this issue. It's nice if we also had binaries for raspberry pis, I'll ask a friend for that.

my last scrutinous hair splitting remark, just edit and rename the zipped files in https://github.com/ericlyon/pd-fftease/releases/tag/3.0.0 to remove "pd-" as the prefix, or add it to the macOS version. I vote for removing it. It'll still decompress to a folder named "fftease" in any case.
