### ISSUE TITLE
Instantiation without arguments

### ISSUE THREAD

**Issue by ericlyon** [ericlyon/pd-fftease#37]
this will be a separate issue, but I think you should allow all objects to be created without any arguments. Some objects here have mandatory arguments and then you can't create the object. In Max, that doesn't prevent you from opening the help file so you know what you have to do, but in Pd you can't do it and I don't think it's a good idea.

_Originally posted by @porres in https://github.com/ericlyon/pd-fftease/issues/26#issuecomment-759915647_

Yes, I agree. That's definitely worth fixing.

**Comment by ericlyon** [comment]
This might be worth fixing for v3.0.2. It would be helpful if anyone has a list of the objects that don't instantiate when missing arguments.

**Comment by Lucarda** [comment]
Open the this patch an see the console.

[fftease-objects.zip](https://github.com/ericlyon/pd-fftease/files/6246486/fftease-objects.zip)

:)

**Comment by ericlyon** [comment]
Tight code :)

**Comment by porres** [comment]
> Open the this patch an see the console.

resent~: must give duration argument
 fftease/resent~
... couldn't create
residency_buffer~: Must specify array name
 fftease/residency_buffer~
... couldn't create
residency~: must give duration argument
 fftease/residency~
... couldn't create
enrich~: Must specify array name
 fftease/enrich~
... couldn't create
pvwarpb~: Must specify array name
 fftease/pvwarpb~
... couldn't create
reanimator~: must include duration argument
 fftease/reanimator~
... couldn't create

**Comment by ericlyon** [comment]
Objects updated. Unless any new bugs are discovered resulting from this update, I'll close this issue in a few days.

**Comment by Lucarda** [comment]
Tested on Linux and Windows and it all seems to work.
