### ISSUE TITLE
disarrain~ helpfile: [showstate( gives error

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#4]
when clicking on the `[showstate(` msgbox in `fftease32-helpfiles/disarrain~-help.pd`, I get a number (e.g. 25) of ugly error messages of the kind:

> $65: argument number out of range

this is because `[pd showbins]` includes a msgbox referencing atoms from `$1` to `$70` (and the incoming message does not hold 70 atoms).

an error-free implementation would simply prepend `set` to the incoming list (of varying length):

```
[inlet]
|
[list prepend set]
|
[list trim]
|
[ (
```

(the needed `[list]` objects have been included since _Pd-0.40_ released somewhen in 2006)

**Comment by ericlyon** [comment]
Yes, that feature was not available when I wrote that help file.
