### ISSUE TITLE
"sound" directory not installed correctly?

### ISSUE THREAD

**Issue by ericlyon** [ericlyon/pd-fftease#44]
Previously the "sound" directory was a sub-directory of "fftease-helpfiles" and needed to be there in order for the Piano sample to load correctly in the pvgrain~ help file. It appears that this folder is not being installed where it should be. May need to manually restore the subdirectory to its previous location.

**Comment by Lucarda** [comment]
> "sound" directory not installed correctly?

It is installed correctly and https://github.com/ericlyon/pd-fftease/blob/master/fftease-helpfiles/pvgrain~-help.pd#L49 finds the file correctly. I think in your case you are running pvgrain~-help.pd from the "repository dir" but you should run from the "install dir". 

You can build and install with:

`make PDLIBDIR=<path/you/want/for/the/install> install` 

Then open _pvgrain~-help.pd_ from your install path and it should load _sound/Piano.aif_

**Comment by ericlyon** [comment]
That explains it - thanks!
