### ISSUE TITLE
time for a new release?

### ISSUE THREAD

**Issue by ericlyon** [ericlyon/pd-fftease#45]
I implemented several minor bug fixes since the last release. Some of the bugs previously prevented some of the help files from properly initializing. The help files are all updated, and are now generally more comprehensive than those in the Max/MSP version of FFTease. So, maybe it's time for a new release. Would that be version 3.0.1? Probably worth some testing first, to make sure I didn't accidentally break anything.
@umlaeute, @porres, @Lucarda

**Comment by Lucarda** [comment]
There are two things I found on first test:

- taint~-help.pd and its init subpatch has the message "taint-scaleexp 0.2;" but this message is not received anywhere (I suspect it goes to the "scaling exponent" slider).

- Many of the help-patches' windows opens too far left or too much at the bottom of the screen.


I'd made PR #46 to fix these.

**Comment by ericlyon** [comment]
Nice catch with taint~, thanks!

**Comment by Lucarda** [comment]
Found a crasher for [pvgrain~] when opening/closing the patch with DSP off (Linux and Windows). Will try to get a back-trace with GDB.

**Comment by ericlyon** [comment]
Is this a new crash for this use case?

**Comment by ericlyon** [comment]
Crash confirmed for macOS as well.

**Comment by ericlyon** [comment]
@Lucarda I think I found the bug. Please try again with the new version.

**Comment by Lucarda** [comment]
Confirmed on Linux and Windows. The crash is gone.

:)

**Comment by Lucarda** [comment]
I'll do more testing tomorrow to see if I found anything else so that 3.0.1 is ready.

**Comment by porres** [comment]
sent a PR updating the icon patch, 3.0.1 sounds about right, just be sure to update this every where it's mentioned ;) (meta.pd / readme, etc)

**Comment by porres** [comment]
will also ask a friend to provide raspberry pi binaries for 3.0.1

**Comment by Lucarda** [comment]
Testing the "help-patches" the only thing that I discover (building current 91937c1 for Win-amd64) is a crasher on **shapee~**. 
If I choose 50 for "shape-width" and I close the patch with DSP ON I get a crash.
It does not happen if I don`t change "shape-width".

**Comment by ericlyon** [comment]
> Testing the "help-patches" the only thing that I discover (building current [91937c1](https://github.com/ericlyon/pd-fftease/commit/91937c1662e6da14d233c514a912f259cf67a636) for Win-amd64) is a crasher on **shapee~**.
> If I choose 50 for "shape-width" and I close the patch with DSP ON I get a crash.
> It does not happen if I don`t change "shape-width".
> 
> EDIT: It also happens on yesterday builds for Linux-amd64

I can't reproduce this crash on macOS. Will investigate.

**Comment by ericlyon** [comment]
@Lucarda - I have a guess of what might be causing the crash. Please try the new version of **shapee~** and let me know if the issue is solved.

**Comment by Lucarda** [comment]
Cool, it got fixed.
Tested on Win/Linux amd64.

:)

**Comment by ericlyon** [comment]
Outstanding. Thanks for confirming the fix!

**Comment by Lucarda** [comment]
Looks like 3.0.1 is ready.

Do we upload to Deken?

**Comment by ericlyon** [comment]
Sure. Do we have all the binaries we need? @porres mentioned getting binaries for raspberry pi.

**Comment by Lucarda** [comment]
Ok I'll prepare win/linux  - i386/amd64 for this repo and for Deken.

**Comment by ericlyon** [comment]
I just drafted a release for v3.0.1. Are you able to access it now (for uploading binaries), or do I have to publish it first?

**Comment by Lucarda** [comment]
I can't access it (as is just drafted). Anyway the only who can upload the binaries is you (I give a link to them and you place them as we did in the past release).

Make the release so I build from that sources.

**Comment by Lucarda** [comment]
> Make the release so I build from that sources.

I meant : publish it.
:)

**Comment by porres** [comment]
I propose the inclusion of a changelog, it can be a very simple one, so we can know what improved in this new 3.0.1 release

as soon as we have a new tagged release in the repository I can help with the binaries

**Comment by porres** [comment]
>  it can be a very simple one

like add a CHANGELOG.txt file to the package, as an example, see https://github.com/porres/pd-cyclone/blob/master/documentation/extra_files/CHANGELOG.txt but it can be simpler than this

**Comment by ericlyon** [comment]
A changelog is a great idea. I was thinking about that too.

**Comment by ericlyon** [comment]
@Lucarda just published it as an alpha release.

**Comment by Lucarda** [comment]
Cool. I'll start building.

**Comment by Lucarda** [comment]
@ericlyon the binaries are [here](https://nc.nubegris.com.ar/index.php/s/gcPKSty9KFtALSM)

**Comment by ericlyon** [comment]
> @ericlyon the binaries are [here](https://nc.nubegris.com.ar/index.php/s/gcPKSty9KFtALSM)

Added to the alpha release, thanks!

**Comment by Lucarda** [comment]
Ok. In a couple of hours I'll upload to Deken.

**Comment by porres** [comment]
I didn't realize I forgot to make the pull request for my icon update after I commited the change in my repository :) 

https://github.com/ericlyon/pd-fftease/pull/47

**Comment by Lucarda** [comment]
Do we use the updated icon on the Deken release?

**Comment by ericlyon** [comment]
> Do we use the updated icon on the Deken release?

That sounds like a good idea.

**Comment by Lucarda** [comment]
Ok I'll do it for the win/linux versions.

**Comment by ericlyon** [comment]
Maybe going forward, the icon should just say "FFTease" rather than include the version number.

**Comment by Lucarda** [comment]
Linux and Windows versions for amd64 and i386 are up on Deken.

:)

**Comment by ericlyon** [comment]
Thanks, @Lucarda! I just updated the macOS binaries in v3.0.1. Can you add those to Deken as well?

**Comment by Lucarda** [comment]
Done. Please check installing it.

**Comment by ericlyon** [comment]
> Done. Please check installing it.

That did not work correctly for me. Selecting [v3.0.1] installed the older 3.0 version.

**Comment by Lucarda** [comment]
Oh, my bad. I used the wrong release. Please wait. :)

**Comment by Lucarda** [comment]
Now? (you might need to restart Pd)

**Comment by ericlyon** [comment]
Now we're good, thanks!

**Comment by Lucarda** [comment]
:)

**Comment by porres** [comment]
so we need a final version tag here (not an alpha) and make it paired with the deken release

and I think it's best when we have a final tagged release here and then, when we're certain it's the final one, we upload that exact one to deken

**Comment by porres** [comment]
> Maybe going forward, the icon should just say "FFTease" rather than include the version number.

I think it's good to have that cleared out when you open the help file, but then, now that I think about it, you do have that information also printed in the terminal for every object and I wasn't considering it. I guess it's just that I also don't really like that information on the terminal as I think it ends up polluting a lot. If the object doesn't create, we do get an error, so I don't know why get a post on the terminal that we loaded the object.

But anyway, of course, it's your call :)

**Comment by ericlyon** [comment]
I see your point, and I'll think about it. I do like seeing the load message in the Pd window, maybe just because I'm used to it, and don't like seeing the version number in the help files.

**Comment by ericlyon** [comment]
> so we need a final version tag here (not an alpha) and make it paired with the deken release
> 
> and I think it's best when we have a final tagged release here and then, when we're certain it's the final one, we upload that exact one to deken

I just added a new v3.0.1 tag. I think it has the same binaries from the alpha, but it also has updates including the new icon, and also a CHANGELOG.txt that I just added to the distro.

**Comment by Lucarda** [comment]
@ericlyon  did you add CHANGELOG.txt to the win/linux packages?
If yes this file should be included in the makefile.

As we (or rather me) are not in a hurry we can correctly update everything via:

1 - I'll make a PR for the makefile
2 - We do newer builds
3 - We upload to Deken

?

**Comment by ericlyon** [comment]
> @ericlyon did you add CHANGELOG.txt to the win/linux packages?
> If yes this file should be included in the makefile.
> 
> As we (or rather me) are not in a hurry we can correctly update everything via:
> 
> 1 - I'll make a PR for the makefile
> 2 - We do newer builds
> 3 - We upload to Deken
> 
> ?

For now it's just in the main distro. There's no rush, so maybe we can integrate the change log in the next release.

Thanks!

**Comment by porres** [comment]
I see we have a oficial 3.0.1 release now => https://github.com/ericlyon/pd-fftease/releases/tag/v3.0.1

I'll ask my friend for raspberry pi binaries

I guess we need to reupload the other packages as well and close this issue then

**Comment by porres** [comment]
by the way, I don't see https://github.com/ericlyon/pd-fftease/blob/master/CHANGELOG.txt provided in the download packages, but don't worry, we can fix this for 3.0.2

I guess you forgot to edit the makefile to also copy this file

**Comment by ericlyon** [comment]
> by the way, I don't see https://github.com/ericlyon/pd-fftease/blob/master/CHANGELOG.txt provided in the download packages, but don't worry, we can fix this for 3.0.2
> 
> I guess you forgot to edit the makefile to also copy this file

I still haven't even looked at the makefile :)

**Comment by porres** [comment]
if you're busy, we can do it ;) 

> @ericlyon did you add CHANGELOG.txt to the win/linux packages?
> If yes this file should be included in the makefile.
> 
> As we (or rather me) are not in a hurry we can correctly update everything via:
> 
> 1 - I'll make a PR for the makefile
> 2 - We do newer builds
> 3 - We upload to Deken

I'm up for that, so?

**Comment by Lucarda** [comment]
I'm out for the weekend but I'm carrying a triple boot (win81/debian32/debian64) netbook. I'll be doing other stuff but I could have a break and compile (and dekenize).

Not sure if I can do extensive tests but I think that had been already done.

:)

**Comment by ericlyon** [comment]
> if you're busy, we can do it ;)
> 
> > @ericlyon did you add CHANGELOG.txt to the win/linux packages?
> > If yes this file should be included in the makefile.
> > As we (or rather me) are not in a hurry we can correctly update everything via:
> > 1 - I'll make a PR for the makefile
> > 2 - We do newer builds
> > 3 - We upload to Deken
> 
> I'm up for that, so?

I just updated the Makefile to include CHANGELOG.txt, so we should be good to go.

Thanks,
Eric

**Comment by Lucarda** [comment]
@porres is there a way to update the sources of the v3.0.1 release?

**Comment by porres** [comment]
no, we need to delete the relase/tag and create a new release, then provide builds that match this exact repository's state ;)

**Comment by ericlyon** [comment]
Maybe this would need to be for v3.0.2 then?

**Comment by porres** [comment]
> Maybe this would need to be for v3.0.2 then?

just for. changelog? Nah... we just update and the announce it

**Comment by umlaeute** [comment]
Am 13. März 2021 00:46:56 MEZ schrieb porres ***@***.***>:
> > Maybe this would need to be for v3.0.2 then?
> 
> just for. changelog? Nah... 

here I agree.

> we just update and the announce it

here I don't.
v3.0.1 has been tagged and released.
that was yesterday. don't try to change the past.

the next release (v3.0.2, v3.1.0, v4.0.0 or whatever it will be called) will contain a changelog.



mfg.igj.fjf
IOhannes

PS: yes you can technically remove tags. even I do this from time to time... but only if the tag was "just pushed" (as in: a couple of minutes ago).
once a tag has been synched to other repositories (eg because somebody else "pulled") changing tags becomes really ugly: unlike force-pushes of commits, these tag changes don't automatically propagate. (you have to manually delete the tag in your local copy, then manually fetch the tags again)

so: please don't change tags once published.

**Comment by porres** [comment]
I'm just confused, I don't know if the 3.0.1 packages in deken are the same as in the 3.0.1 tag here.

If so, we can just forget about it and close this issue if we're not sure if we'll re upload with a changelog included or not.

Again, having a new 3.0.2 release just to say a changelog is included in the package seems overkill. 

> that was yesterday

it was about 2 weeks ago now :)

**Comment by porres** [comment]
Well, I guess we can close this, huh? Here's the raspberry pi binaries I promised, I also have the lyonpotpourri as well

upload them to github and deken please ;)
[fftease-3.0.1_arm.zip](https://github.com/ericlyon/pd-fftease/files/6173844/fftease-3.0.1_arm.zip)
[lyonpotpourri-3.0.0_arm.zip](https://github.com/ericlyon/pd-fftease/files/6173846/lyonpotpourri-3.0.0_arm.zip)

**Comment by ericlyon** [comment]
> Well, I guess we can close this, huh? Here's the raspberry pi binaries I promised, I also have the lyonpotpourri as well
> 
> upload them to github and deken please ;)
> [fftease-3.0.1_arm.zip](https://github.com/ericlyon/pd-fftease/files/6173844/fftease-3.0.1_arm.zip)
> [lyonpotpourri-3.0.0_arm.zip](https://github.com/ericlyon/pd-fftease/files/6173846/lyonpotpourri-3.0.0_arm.zip)

Great, thanks! Updating now.

**Comment by porres** [comment]
note you have 4 different binaries for arm/raspberry pi, I'm not sure we need them all actually, but I've been uploading these 4 versions for my libraries.

**Comment by porres** [comment]
perhaps @umlaeute can helps us figure out a better way to package these as a single package for all (and save space in deken's server)

**Comment by umlaeute** [comment]
use arch specific extensions for the externals: l_arm, l_amd64, l_i386, m_i386, m_amd64, d_fat
(either rename the files, or build them with the proper extension using pd-lib-builder's "extension".

its not very complicated...

**Comment by porres** [comment]
I see, that's I already do for mac so I can make the fat binaries for both 32/64 bits, like:

"make install objectsdir=../ extension=d_fat"

so, that's it, tight? We just replace "d_fat" for these others, oh, wait, there's a d_fat for linux too :) 

well, I'm including @emviveros here, cause he was the one who compiled these for us!

I guess we need to be sure which extensions is which for the 4 raspberry pi variants he compiles.

Namely, they are:

pd-fftease-3.0.1_**armv6_Linux32**
pd-fftease-3.0.1_**armv7_Linux32**
pd-fftease-3.0.1_**armv8_Linux32**
pd-fftease-3.0.1_**armv8_Linux64**

dear @umlaeute , could you help us with the exact binary for each? I'll do the same for the next release of ELSE so we can save more space in the server

And while we're at it, I guess a single package for the 2 other versions of linux and windows (32/64 bits on both cases) would be nice too.

**Comment by ericlyon** [comment]
I recently tested the current raspberry pi builds of FFTease and LyonPotpourri on an Organelle M. Works great. Pretty sure I used the armv6 package.

**Comment by porres** [comment]
Ok, by checking the latest zexy in deken, I'm guessing the packages and extensions are:

Darwin-amd64 = .pd_darwin;
Linux-amd64-32 = .pd_linux;
Linux-arm64-32 = .l_arm64;
Linux-armv7-32 = .l_arm
Linux i386-32 = .l_i386
Windows-amd64-32 = .m_amd64
Windows-i386-32 = .dll

**Comment by porres** [comment]
> use arch specific extensions for the externals: l_arm, l_amd64, l_i386, m_i386, m_amd64, d_fat

Now I get you put extensions not only for linux/arm, like d_fat for macOS and m_amd64 for windows, right?

> Ok, by checking the latest zexy in deken, I'm guessing the packages and extensions are:
> 
> Darwin-amd64 = .pd_darwin;
> Linux-amd64-32 = .pd_linux;
> Linux-arm64-32 = .l_arm64;
> Linux-armv7-32 = .l_arm
> Linux i386-32 = .l_i386
> Windows-amd64-32 = .m_amd64
> Windows-i386-32 = .dll

@emviveros buils two packages that are not exemplified here:

pd-fftease-3.0.1_**armv6_Linux32**
pd-fftease-3.0.1_**armv8_Linux32**

we'd still need to figure out which they'd be

**Comment by porres** [comment]
> I recently tested the current raspberry pi builds of FFTease and LyonPotpourri on an Organelle M. Works great. Pretty sure I used the armv6 package.

Nice, how did you do it? Does the organelle connect directly to deken? :)

**Comment by ericlyon** [comment]
Their Pd is Read-only, so I had to upload the externals manually. No deken. It's a fun little box tho!

**Comment by porres** [comment]
I can see you having a great joy running these externals there ;)

> No deken. It's a fun little box tho!

a good reason to have them here on the repository then :)

**Comment by umlaeute** [comment]
> 
> @emviveros buils two packages that are not exemplified here:
> 
> pd-fftease-3.0.1_**armv6_Linux32**
> pd-fftease-3.0.1_**armv8_Linux32**
> 
> we'd still need to figure out which they'd be

there are no specific file extensions for the 32bit arm variants: all use `.l_arm` (or `.pd_linux` if you want).

`armv6` is required to run the external on the RPi Zero/RPi 1 (and the "compute module", but that's probably not important).
given that these platforms are typically very limited, i think it would make most sense to not combine packages for these architecture with other archs.

i'm not sure whether the `armv8` variant is really that useful (that is: whether there are significant performance improvements with respect to the `armv7` variant). others [seem to wonder as well](https://community.arm.com/developer/ip-products/processors/f/cortex-a-forum/8613/armv7-vs-armv8-aarch32-performance-improvement).
also, i'm not sure whether there are pre-built binaries of Pd for `armv8` (Raspbian uses `armv6`, Debian uses `armv7`).
a Pd-armv7 would not (automatically) detect that it can run `armv8` externals (although you could explicitly ask for that architecture via the deken-settings).
if somebody builds a Pd-armv8 themselves, they can probably build optimized externals as well.

**Comment by ericlyon** [comment]
Both LyonPotpourri and FFTease compile on the Organelle with no problems. Although Pd is installed on a read-only partition on the Organelle, it can be remounted as rw, after which 3rd party externals can be installed as usual. Deken also works in rw mode.

**Comment by porres** [comment]
> i'm not sure whether the armv8 variant is really that useful (that is: whether there are significant performance improvements with respect to the armv7 variant). others seem to wonder as well.

Actually, @emviveros was telling me we should probably just forget about this architecture, he didn't say why, but you're basically saying the same, so I guess that solves it :) 

> armv6 is required to run the external on the RPi Zero/RPi 1 (and the "compute module", but that's probably not important).

Yeah, probably obscure enough to also forget about it...

> also, i'm not sure whether there are pre-built binaries of Pd for armv8 (Raspbian uses armv6, Debian uses armv7).

I'm confused now, does this mean Raspbian is just for RPi Zero/1? 

And the, @ericlyon  says he was running it on the organelle, and I bet that's not RPi 1!

> a Pd-armv7 would not (automatically) detect that it can run armv8 externals (although you could explicitly ask for that architecture via the deken-settings).

Is the organelle like that with armv6 as well? And since it can run deken, what will it see? We have separate packages for else up in deken, we can try...

**Comment by emviveros** [comment]
> there are no specific file extensions for the 32bit arm variants: all use `.l_arm` (or `.pd_linux` if you want).
> 
> `armv6` is required to run the external on the RPi Zero/RPi 1 (and the "compute module", but that's probably not important).

"compute module" are not important since **RPizero variants are important**,  so armv6 should be disponible.

> i'm not sure whether the `armv8` variant is really that useful (that is: whether there are significant performance improvements with respect to the `armv7` variant). others [seem to wonder as well](https://community.arm.com/developer/ip-products/processors/f/cortex-a-forum/8613/armv7-vs-armv8-aarch32-performance-improvement).

about armv8 usefullness, I have two points come to my mind:
1. two variants of armv8 I don't think anymore it's important and should be abandoned in favor of armv8 64bits (AARCH64).
2. in ELSE development we have feedback of armv7 binaries initialization failing in RPi4 platforms, reason for what I started to compile armv8 binaries for ELSE.

resuming, for 64bit arm platforms RPi compatible, should be disponible aarch64 (armv8 64bits) binaries.

**Comment by emviveros** [comment]
My first annoying is how to name armv6, armv7 and armv8 binaries to create a unified deken package for arm compilations.

**Comment by porres** [comment]
> armv6 = ?? (maybe .pd_linux)

well, yeah, if we have just a package for raspbrry pis, then we can pack these 3 together, of course!!!

pd_linux was listed for Linux-amd64-32 (regular 64 bits Linux), so the problem would be to pack this with it as well - unless there's something else specfic for this architecture.

Anyway,  I guess it makes sense to pack the 3 pi versions together, then the 2 linux also together (32/64 bits), then windows in the same way (32/64) and the mac fat binary for both 32/64 bits. 4 Packages instead of 8!

**Comment by ericlyon** [comment]
@porres - else packages show up on Deken in Linux-armv6-32 format for the Organelle.

**Comment by emviveros** [comment]
> well, yeah, if we have just a package for raspbrry pis, then we can pack these 3 together, of course!!!

in that way, we don't will have problems choosing .pd_linux for armv6.

**Comment by porres** [comment]
> else packages show up on Deken in Linux-armv6-32 format for the Organelle

so i'm confused, is the organelle a rasp 1?

**Comment by porres** [comment]
anyway, let's just have these 3 together and I guess there won't be any issues :)

**Comment by ericlyon** [comment]
> > else packages show up on Deken in Linux-armv6-32 format for the Organelle
> 
> so i'm confused, is the organelle a rasp 1?

I'm told that it's a Raspberry Pi 3 module running their debian based distro.

**Comment by umlaeute** [comment]
sigh.
i think this is the **totally wrong place** to discuss these matters.
it has very little to do with fftease, but instead is of general interest.
shouldn't we take this to the pd-dev list?

(i'm going to answer over there)
