### ISSUE TITLE
[disarrain~] crashes when testing under Double-precision

### ISSUE THREAD

**Issue by Lucarda** [ericlyon/pd-fftease#49]
I came into this while testing fftease-3.0.1 for Pd-Double precision running on Debian Buster amd64.

Just opened the help patch several times (and several crashes) and the terminal gave me some clues:

![disarrain_](https://user-images.githubusercontent.com/25239522/113241230-9e0e2e80-9284-11eb-969c-bcd17d6e8070.png)

**Comment by ericlyon** [comment]
Does this happen with the DACs off too?

**Comment by Lucarda** [comment]
> Does this happen with the DACs off too?

nope.

**Comment by ericlyon** [comment]
Does the crash happen immediately when you turn on the DACs, after loading the helpfile with DACs off?

**Comment by Lucarda** [comment]
Not immediately but after a couple of seconds some test. On other test I cant reproduce anymore. This time I start Pd, open the patch with dsp off and switch dsp on. <-- now I dont get the crash.

**Comment by ericlyon** [comment]
Thanks. This seems like a memory bug. Are you able to produce the crash on 32-bit also, or only 64-bit Pd? To recap:

1) load disarrain~ with DACs off, then turn DACs on: no crashes
2) load disarrain~ with DACs on, after a while there might be a crash (or not)

Correct?

**Comment by Lucarda** [comment]
> Thanks. This seems like a memory bug. Are you able to produce the crash on 32-bit also, or only 64-bit Pd?

I got it on Pd(64bit)(double-precision).
note: I think I never got into this while testing **single-precision** i386/amd64

>load disarrain~ with DACs off, then turn DACs on: no crashes
load disarrain~ with DACs on, after a while there might be a crash (or not)
Correct?

Correct but now I can't get the crash again. :(

**Comment by ericlyon** [comment]
OK very helpful. I see the bug now, and it is a memory issue. I also understand why it crashes on Pd-64 but not Pd-32. See if you can spot it too :) 

I won't have time to fix it tonight, but maybe tomorrow. It should be an easy fix.

**Comment by Lucarda** [comment]
Ok no trouble.

I could reproduce if:

- 1 - start Pd with dsp on
- 2 - open the help browser and go to externals/fftease
- 3 - open (for a couple of seconds) and close the help patches alphabetically
- 4 - when I open disarrain~help I get the crash.

PS: It seems that Fftease for Pd-Double is already made :)

**Comment by Lucarda** [comment]
> See if you can spot it too :)

:) I rather say this line and the next one?

https://github.com/ericlyon/pd-fftease/blob/d31a1e428e18ea85e8e68cd696085059194807f0/disarrain~.c#L130

**Comment by ericlyon** [comment]
> > See if you can spot it too :)
> 
> :) I rather say this line and the next one?
> 
> https://github.com/ericlyon/pd-fftease/blob/d31a1e428e18ea85e8e68cd696085059194807f0/disarrain~.c#L130

I believe you found the bug :)

**Comment by Lucarda** [comment]
Yes. At least testing with my libpkgtester[1] the crash is gone.

You will find it very useful to go throw help patches.

[libpkgtester.zip](https://github.com/ericlyon/pd-fftease/files/6241487/libpkgtester.zip)


[1] a collection of 3 or 4 old externals into a single binary + a patch. You can compile it with `make install`.

:)

**Comment by ericlyon** [comment]
> Yes. At least testing with my libpkgtester[1] the crash is gone.
> 
> You will find it very useful to go throw help patches.
> 
> [libpkgtester.zip](https://github.com/ericlyon/pd-fftease/files/6241487/libpkgtester.zip)
> 
> [1] a collection of 3 or 4 old externals into a single binary + a patch. You can compile it with `make install`.
> 
> :)

Cool, thanks!

**Comment by ericlyon** [comment]
Code updated. Hopefully it's safe to close this issue.
