### ISSUE TITLE
burrow~: loadbanged "invert" has not effect

### ISSUE THREAD

**Issue by umlaeute** [ericlyon/pd-fftease#5]
the `[invert 1(` message loadbanged in the _burrow~-help.pd_ seems to have no effect.

at least toggling to `[invert 0(` sounds very much the same, but when I toggle back to `[invert 1(` the output changes.

**Comment by ericlyon** [comment]
I can confirm this malfunction, which will require some investigation.

**Comment by porres** [comment]
@umlaeute we can close this one too

**Comment by umlaeute** [comment]
shouldn't we instead close #27, which is a duplicate created 5 years and doesn't add much additional info?

**Comment by porres** [comment]
both are to be closed as there's already a solution, the other is still open just because in the discussion we have a reminder to pull out a post message

**Comment by ericlyon** [comment]
I just removed the post() message, so feel free to close the issue.

**Comment by porres** [comment]
cool, I you could just close both as well @ericlyon  :)

**Comment by ericlyon** [comment]
> cool, I you could just close both as well @ericlyon :)

Just trying to give people space to do whatever :)
